### ISSUE TITLE
Angular 10 have error

### ISSUE THREAD

**Issue by spawnborn** [Cordobo/angularx-qrcode#93]
error when run in angular 10

**Comment by Cordobo** [comment]
Damn, I knew it :)

I had no time to test the lib against A10 yet, but if you did, do you mind to share some more details?

PR's are always welcome!

**Comment by mhov** [comment]
`ERROR in ./node_modules/angularx-qrcode/node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js 5888:12-27
"export 'ɵlooseIdentical' was not found in '@angular/core'`

**Comment by mhov** [comment]
this PR https://github.com/Cordobo/angularx-qrcode/pull/94 just shows how i got rid of the error, not necessarily how main should be fixed

**Comment by Cordobo** [comment]
Yes, the build would break for older versions. I had the exact same problem with the last versions. I still don't know a better way to get around this other than a new release for each major angular version.

**Comment by Cordobo** [comment]
angularx-qrcode 10 has been released for angular 10
